DROP TABLE IF EXISTS MODE;
DROP TABLE IF EXISTS PATIENT;
DROP TABLE IF EXISTS ALARM;
DROP TABLE IF EXISTS STATE;
DROP TABLE IF EXISTS BOUNDARIES;


CREATE TABLE IF NOT EXISTS MODE (
	id INTEGER PRIMARY KEY,
   	start_time TEXT DEFAULT CURRENT_TIMESTAMP,
	mode VARCHAR(10) NOT NULL,
	patient_id INTEGER NOT NULL,
	FIO2 INTEGER DEFAULT NULL,
	shape INTEGER DEFAULT NULL,
	riseTime INTEGER DEFAULT NULL,
	tIns INTEGER DEFAULT NULL,
	tInsMax INTEGER DEFAULT NULL,
	Freq INTEGER DEFAULT NULL,
	vTidal INTEGER DEFAULT NULL,
	vMin INTEGER DEFAULT NULL,
	flow REAL DEFAULT NULL,
	pCon REAL DEFAULT NULL,
	pSuport REAL DEFAULT NULL,
	tSup REAL DEFAULT NULL,
	pSup REAL DEFAULT NULL,
	tInf REAL DEFAULT NULL,
	pInf REAL DEFAULT NULL,
	PEEP REAL DEFAULT NULL,
	sensInsP REAL DEFAULT NULL,
	sensInpF REAL DEFAULT NULL,
	tPausaIns INTEGER DEFAULT NULL,
	sensExpF REAL DEFAULT NULL,
	pInsLimit REAL DEFAULT NULL,
	bkMode INTEGER DEFAULT NULL,
	bkTIns INTEGER DEFAULT NULL,
	bkFreq INTEGER DEFAULT NULL,
	bkVTidal INTEGER DEFAULT NULL,
	bkPcon REAL DEFAULT NULL,
	FOREIGN KEY (patient_id) REFERENCES PATIENT (id)
		ON UPDATE CASCADE 
		ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS PATIENT (
	id INTEGER PRIMARY KEY,
	age_group VARCHAR(10) NOT NULL,
	name VARCHAR(100) DEFAULT NULL,
	weight INTEGER DEFAULT NULL,
	height INTEGER DEFAULT NULL,
	prontuary INTEGER DEFAULT NULL,
	sex VARCHAR(10) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS ALARM (
	id INTEGER PRIMARY KEY,
	type VARCHAR(10) NOT NULL,
	mode_id INTEGER DEFAULT NULL,
	start_time TEXT DEFAULT CURRENT_TIMESTAMP,
	end_time TEXT DEFAULT CURRENT_TIMESTAMP,
	message VARCHAR(100) DEFAULT NULL,
	value REAL DEFAULT NULL,
	num_silences INTEGER DEFAULT 0,
	state INTEGER DEFAULT 1,
	FOREIGN KEY (mode_id) REFERENCES MODE (id)
		ON UPDATE RESTRICT
		ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS BOUNDARIES (
	id INTEGER PRIMARY KEY,
	mode_id INTEGER DEFAULT NULL,
	start_time TEXT DEFAULT CURRENT_TIMESTAMP,
	notBreathing REAL DEFAULT NULL,
	fio2min INTEGER DEFAULT NULL,
	fio2max INTEGER DEFAULT NULL,
	vMinMin INTEGER DEFAULT NULL,
	vMinMax INTEGER DEFAULT NULL,
	pInsMin REAL DEFAULT NULL,
	pInsMax REAL DEFAULT NULL,
	pInsHardLimit REAL DEFAULT NULL,
	freqMax INTEGER DEFAULT NULL,
	vTidalInsMin INTEGER DEFAULT NULL,
	vTidalInsMax INTEGER DEFAULT NULL,
	maxPEEP REAL DEFAULT NULL,
	FOREIGN KEY (mode_id) REFERENCES MODE (id)
		ON UPDATE RESTRICT
		ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS STATE (
	id INTEGER PRIMARY KEY,
	shutdown INTEGER DEFAULT 1,
	hourmeter INTEGER default 3,
	strategy VARCHAR(200) DEFAULT '{}',
	boundaries VARCHAR(200) DEFAULT '{}',
	patient VARCHAR(200) DEFAULT '{}'
);

INSERT INTO STATE DEFAULT VALUES;
